const events = document.querySelectorAll('.event');
const details = document.getElementById('details');

const data = {

gaj: {
title: "1830. – Gajeva pravopisna reforma",
text: `Ljudevit Gaj bio je jedan od najvažnijih vođa hrvatskog narodnog preporoda. 
Njegova pravopisna reforma iz 1830. godine bila je ključna za standardizaciju hrvatskog jezika. 
Prije toga, u hrvatskom pisanju koristilo se više različitih pravopisnih sustava, što je otežavalo komunikaciju i razvoj književnosti.

Gaj je uveo jedinstveni sustav pisanja temeljen na latinici, uključujući slova poput č, ć, š i ž. 
Ova reforma omogućila je razvoj modernog hrvatskog književnog jezika i bila je temelj za kasniji kulturni razvoj.

Osim toga, Gaj je bio politički aktivan i zalagao se za kulturno i političko ujedinjenje južnih Slavena.
Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?`},

novine: {
title: "1834. – Ilirske novine",
text: `Ilirske novine bile su prve novine tiskane na hrvatskom jeziku koje su imale politički i kulturni značaj. 
Pokrenuo ih je Ljudevit Gaj, a igrale su ključnu ulogu u širenju ideja ilirskog pokreta.

Putem novina širila se svijest o važnosti jezika, kulture i nacionalnog identiteta. 
Također su informirale javnost o političkim događajima i poticale rasprave o položaju Hrvatske unutar Habsburške Monarhije.

Ilirske novine bile su važan korak prema stvaranju modernog hrvatskog društva.

ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?`},

jezik: {
title: "1847. – Hrvatski jezik postaje službeni",
text: `Godine 1847. Hrvatski sabor donio je odluku da hrvatski jezik postane službeni jezik u javnoj uporabi, 
umjesto latinskog koji se dotad koristio u administraciji.

Ova odluka bila je izuzetno važna za razvoj nacionalnog identiteta i kulture. 
Omogućila je većem broju ljudi sudjelovanje u javnom životu jer su mogli koristiti vlastiti jezik.

Time je hrvatski jezik dobio institucionalnu podršku i postao ključni element nacionalnog jedinstva.

ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?`},

"1848": {
title: "1848. – Revolucija i ban Josip Jelačić",
text: `Revolucionarna 1848. godina donijela je velike promjene diljem Europe, pa tako i u Hrvatskoj. 
Ban Josip Jelačić postao je simbol borbe za autonomiju Hrvatske unutar Habsburške Monarhije.

Jedna od njegovih najvažnijih odluka bila je ukidanje kmetstva, čime su seljaci dobili osobnu slobodu. 
Također se suprotstavio mađarskim vlastima koje su pokušavale centralizirati vlast.

Jelačić je ostao zapamćen kao jedan od najvažnijih političkih vođa u hrvatskoj povijesti.

ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?`},

nagodba: {
title: "1868. – Hrvatsko-ugarska nagodba",
text: `Hrvatsko-ugarska nagodba bila je sporazum kojim su definirani odnosi između Hrvatske i Ugarske unutar Austro-Ugarske Monarhije.

Iako je Hrvatska dobila određeni stupanj autonomije, mnogi su smatrali da je nagodba nepovoljna jer je stvarna politička moć ostala u rukama ugarske vlasti.

Nagodba je obilježila politički život Hrvatske u drugoj polovici 19. stoljeća i izazvala brojne rasprave i nezadovoljstvo.

ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?`},

kraj: {
title: "Kraj 19. stoljeća – politički razvoj",
text: `Krajem 19. stoljeća u Hrvatskoj se razvijaju političke stranke i moderni politički sustav. 
Pojavljuju se ideje o većoj autonomiji i neovisnosti Hrvatske.

Industrijalizacija i razvoj gradova dovode do društvenih promjena, a obrazovanje i kultura postaju sve važniji.

Ovo razdoblje postavilo je temelje za događaje u 20. stoljeću i daljnju borbu za hrvatsku državnost.

ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?

Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni odio excepturi, perferendis exercitationem rem, repellendus molestiae corrupti aliquam ipsam alias ipsa provident autem. Labore reprehenderit aliquam provident. A consequatur molestiae quidem aliquid exercitationem sed sunt soluta optio dolores accusantium! Soluta hic repellat ea, accusamus laudantium est id ducimus sequi magnam cum minima eum, a odio vitae sint. Labore ducimus, nemo blanditiis eos cumque, odio ut reprehenderit tempore quos fuga minus velit facilis deleniti repellendus modi quidem recusandae aliquid provident praesentium culpa! Necessitatibus possimus doloremque excepturi incidunt ullam cupiditate repellat, minima corrupti veritatis praesentium non a illum quod labore suscipit dolorum nam ipsa maiores totam repellendus? Blanditiis excepturi itaque numquam dolorum consectetur ratione id corrupti architecto dolore! Excepturi facere libero voluptate cupiditate nihil soluta molestias alias quos esse, necessitatibus a voluptatum pariatur delectus atque, quibusdam quia officia laudantium non, dolorem ad error illo sunt distinctio. Voluptas voluptate qui fugiat incidunt dolorem iusto, nobis, aperiam dolore, laudantium ut sequi? Quod saepe, culpa deserunt explicabo consequatur, itaque facilis dolore vel tenetur voluptates illo? Perspiciatis cupiditate obcaecati laboriosam excepturi repellat quasi officiis explicabo quaerat ut aut? Facilis quaerat quas dolor iusto distinctio possimus modi saepe ex accusantium, molestias, sed corporis a, ratione autem perferendis unde. Ducimus velit doloremque eaque recusandae explicabo quod fugiat cupiditate, facere pariatur sapiente odio perferendis quisquam consequatur veritatis possimus nobis distinctio vero molestias qui culpa! Magni quam assumenda, aperiam amet quae consectetur voluptatibus? A ex, dolorem laborum, illo tempora, accusamus porro odit praesentium nam omnis cum voluptatum id quod error quos ea sunt ipsam eum autem placeat possimus. Vero earum illum impedit consequatur nostrum eligendi at id fugiat dolorum labore hic ullam voluptatibus repellendus quasi rerum fuga tempora quos consequuntur sint, culpa atque odio ad? Iste, voluptates. Debitis velit dolores non magni officia vitae alias a illum tempore, similique sequi?`}

};

events.forEach(event => {
    event.addEventListener('click', () => {
        const id = event.dataset.id;
        details.innerHTML = `
            <h2>${data[id].title}</h2>
            <p>${data[id].text}</p>
        `;
    });
});